name: Daily N2YO Parser

on:
  schedule:
    # Запуск каждый день в 19:01 по МСК (16:01 по UTC)
    - cron: '0 13 * * *'
  workflow_dispatch: 

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb

    - name: Install Python dependencies
      run: |
        pip install pyvirtualdisplay undetected-chromedriver selenium gspread google-api-python-client google-auth requests

    - name: Create credentials.json
      run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json

    - name: Run Python script
      run: python bot.py
