name: Daily N2YO Parser

on:
  schedule:
    # Запуск каждый день в 18:55 МСК (15:55 UTC)
    - cron: '55 15 * * *'
  workflow_dispatch: 

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # Устанавливаем системный пакет для виртуального монитора
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb

    # Устанавливаем новые скрытные библиотеки для Python
    - name: Install Python dependencies
      run: |
        pip install pyvirtualdisplay undetected-chromedriver selenium gspread google-api-python-client google-auth

    - name: Create credentials.json
      run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json

    - name: Run Python script
      run: python bot.py
